In [2]:
import torch
varT = torch.tensor([1, 2, 3])
type(varT)
varT[0] = 5
varT

tensor([5, 2, 3])

In [3]:
### tf 예시
import tensorflow as tf
var = tf.Variable([100,200,300])
type[var]
# var[0] = 1 // TF는 이거 안됨 assing써야 함

var[0].assign(1)
var

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([  1, 200, 300])>

In [4]:
a=tf.Variable([4,5,6])
b=tf.constant([1,2,3])
# variable은 주소와 함께! b는 주소X
a, b

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>)

In [5]:
aa=[7,8,9]
b=tf.constant(aa)
b, tf.convert_to_tensor(aa)

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 8, 9])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 8, 9])>)

In [2]:
#### -- 1-2. 분석 환경 설정 -- ####
import torch
is_cuda = torch.cuda.is_available()
device = torch.device('cuda' if is_cuda else 'cpu')

print ('Current cuda device is', device)

Current cuda device is cuda


In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
datagen = ImageDataGenerator(rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True # 이미지의 절반을 무작위로 수평으로 뒤집습니다.
    )
test_gen = ImageDataGenerator(rescale=1./255)

from sklearn.model_selection import train_test_split

# Split the original training data into training and validation
train_df, valid_df = train_test_split(train_df, test_size=0.2, random_state=42)

train_gen = datagen.flow_from_dataframe(dataframe=train_df, directory=None, x_col='path', y_col='label',
    weight_col=None, target_size=(256, 256), color_mode='rgb',
    classes=None, class_mode='categorical', batch_size=32, shuffle=True)

# Create a new generator for validation data
valid_gen = datagen.flow_from_dataframe(dataframe=valid_df, directory=None, x_col='path', y_col='label',
    weight_col=None, target_size=(256, 256), color_mode='rgb',
    classes=None, class_mode='categorical', batch_size=32, shuffle=True)

test_gen = test_gen.flow_from_dataframe(dataframe = test_df, directory=None, x_col='path', y_col='label',
    weight_col=None, target_size=(256, 256), color_mode='rgb',
    classes=None, class_mode='categorical', batch_size=32, shuffle=True)